set runtimepath=~/vimfiles,$VIMRUNTIME

" Setup vim-plug https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation
let data_dir = has('nvim') ? stdpath('data') . $HOME.'/site' : $HOME.'/vimfiles'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
Plug 'cocopon/iceberg.vim'
Plug 'vim-airline/vim-airline'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
call plug#end()


" Terminal Output Codes
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

" Editor Options
set encoding=utf-8
set number
set backspace=indent,eol,start

set showcmd
set showmatch
set scrolloff=5

set ignorecase
set smartcase
set hlsearch
set incsearch

set splitbelow

set wildmenu
set wildmode=longest,list,full

set expandtab
set tabstop=2
set shiftwidth=0

set shell=\"C:\Program\ Files\PowerShell\7\pwsh.exe\"

set t_Co=256
set background=dark
syntax on
colorscheme iceberg

" Set the default listing style to tree.
let g:netrw_liststyle = 3

" Make vertical splitting the default for previewing files.
" Split the preview window into the right side.
let g:netrw_preview = 1
let g:netrw_alto = 0

" When a vertical preview window is opened, the directory listing
" will use only 20% of the columns available; the rest of the window
" is used for the preview window.
let g:netrw_winsize = 20

" Key Mappings
nnoremap <silent> <F5> :w<CR>:source $MYVIMRC<CR>
nnoremap <silent> <C-[><C-[> :noh<CR>
nnoremap <silent> <Space><Space> :let @/ = '\<' . expand('<cword>') . '\>'<CR>:set hlsearch<CR>
nnoremap <silent> gl :ls<CR>
nnoremap <silent> gb :bn<CR>
nnoremap <silent> gB :bp<CR>
nnoremap <silent> g= :set lazyredraw<CR>gg=G`'zz:set nolazyredraw<CR>
nnoremap <silent> gyy "*yy
nmap <Space>h <Space><Space>:%s/<C-r>///g<Left><Left>

vnoremap <silent> gy "*y

cnoremap <C-a> <C-b>

" Autocommands
autocmd CmdlineEnter * call echoraw(&t_SI)
autocmd CmdlineLeave * call echoraw(&t_EI)
