" Setup vim-plug https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation
let data_dir = has('nvim') ? stdpath('data') . $HOME.'/site' : $HOME.'/vimfiles'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
Plug 'cocopon/iceberg.vim'
Plug 'vim-airline/vim-airline'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
call plug#end()


" Terminal Output Codes
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

" Editor Options
set encoding=utf-8
set number

set showcmd
set showmatch
set scrolloff=5

set ignorecase
set smartcase
set hlsearch
set incsearch

set splitbelow

set wildmenu
set wildmode=longest,list,full

set expandtab
set tabstop=2
set shiftwidth=0

set shell=\"C:\Program\ Files\PowerShell\7\pwsh.exe\"

set t_Co=256
syntax on
colorscheme iceberg

" Key Mappings
nnoremap <silent> <F5> :w<CR>:source $MYVIMRC<CR>
nnoremap <silent> <C-[><C-[> :noh<CR>
nnoremap <silent> <Space><Space> :let @/ = '\<' . expand('<cword>') . '\>'<CR>:set hlsearch<CR>
nnoremap <silent> gl :ls<CR>
nnoremap <silent> gb :bn<CR>
nnoremap <silent> gB :bp<CR>
nnoremap <silent> g= :set lazyredraw<CR>gg=G`'zz:set nolazyredraw<CR>
nmap <Space>h <Space><Space>:%s/<C-r>///g<Left><Left>

cnoremap <C-a> <C-b>

" Autocommands
autocmd CmdlineEnter * call echoraw(&t_SI)
autocmd CmdlineLeave * call echoraw(&t_EI)
