[shell]
program = "C:/Program Files/PowerShell/7/pwsh.exe"
args = ["-NoLogo", "-wd" , "~"]

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "W", mods = "Control|Shift", action = "Quit" },
]
