[shell]
program = "C:\\WINDOWS\\system32\\wsl.exe"
args = ["~"]

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "W", mods = "Control|Shift", action = "Quit" },
]
